<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/graceng/AI/Threlte/mimes-lp2/static/models/skyline.glb --root /models/ --types --printwidth 120 --precision 2
Author: MozillaHubs (https://sketchfab.com/mozillareality)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skyline-cutout-city-large-b00abd35578e4f628f4bcd3625ce5951
Title: Skyline Cutout - City - large
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      SkylineCutoutLarge_lambert2_0: THREE.Mesh
    }
    materials: {
      lambert2: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/skyline.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.SkylineCutoutLarge_lambert2_0.geometry}
          material={gltf.materials.lambert2}
          position={[0, 0, -4361]}
          scale={500}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
