<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /Users/graceng/AI/Threlte/mimes-lp2/static/models/spiderman.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'animation'
  type GLTFResult = {
    nodes: {
      mesh: THREE.SkinnedMesh
      hips: THREE.Bone
    }
    materials: {
      ['Default OBJ']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/spiderman.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="animation" position={[0, 0.22, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.85}>
        <T is={gltf.nodes.hips} />
        <T.SkinnedMesh
          name="mesh"
          geometry={gltf.nodes.mesh.geometry}
          material={gltf.materials['Default OBJ']}
          skeleton={gltf.nodes.mesh.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
